### ISSUE TITLE
Reduce serialisation size

### ISSUE THREAD

**Issue by TimonPost** [amethyst/serde-diff#12]
Thanks for this awesome crate. I just exactly need this for serializing entity changes before sending them over the network. Though I have one big concern. The size of the JSON that it outputs. 

Are there any plans to improve this in the future? I can work to invest some time into this. 

Currently, we have those tag names:

```rust
enum DiffCommandField {
    Enter,
    Value,
    Remove,
    AddKey,
    EnterKey,
    RemoveKey,
    Exit,
}

pub enum DiffPathElementValue<'a> {
    /// A struct field
    #[serde(borrow)]
    Field(Cow<'a, str>),
    FieldIndex(u16),
    CollectionIndex(usize),
    AddToCollection,
}
```
Those fields will be passed into the end serialization result. I think that this is completely unnessiscarly. 

I am thinking about solutions to make those fields smaller or allow the user to specify their preference. For example, we can use the enum tag index instead of enum tag name. This would fit into a single byte. 

Do you have any idea on how to make this smaller and more compact?

**Comment by TimonPost** [comment]
I just found this comment;

```
//TODO: Currently we store data as a command list that encodes the hierarchy, i.e.
// [{"Enter":{"Field":"a"}},{"Value":3.0},{"Enter":{"Field":"c"}},{"Enter":{"Field":"x"}},{"Value":39.0}]
// Value is decoded as an implicit Exit to avoid excessive Exits in the data stream.
// It could probably be made smaller and more readable in a text-based format.
```

So let's discuss this further in this issue.

**Comment by kabergstrom** [comment]
Hi, thanks for interest in the crate!

The main reason for the large messages in JSON (and bincode) is the encoding of enum variants. MessagePack serializes numbers as varints, and produces significantly smaller messages compared to bincode which encodes numbers as 32-bit or 64-bit. Would the MessagePack sizes be acceptable for you or do you want to work towards an even more compact representation?
PTAL the discussion here:
https://github.com/amethyst/serde-diff/pull/11

Unfortunately rmp-serde has an issue where it doesn't properly advertise itself as a non-human readable format, please take a look at this issue that ended up as a result of trying to fix that: https://github.com/3Hren/msgpack-rust/issues/235

**Comment by TimonPost** [comment]
The message pack would probably better then. One question I had is, does this crate cause the enum tags to be added to the end serialization result or do the serializer like serde json, msg pack that? 

Can't we customize how we want enums to be serialized?

**Comment by kabergstrom** [comment]
This crate just uses `#[derive(Serialize, Deserialize)]` for serializing the sequence of Commands (which are enums) currently, so it is up to the serde format to encode it efficiently. The Serialize impl could be customized, but I think another option is to convert the command stream to a different structure that can be serialized more efficiently for the format you are using. For example, JSON may encode map structures much more concisely than sequences.

**Comment by kabergstrom** [comment]
Please try MessagePack first though, see if the messages are small enough for your use-case. The overhead shouldn't be that large - try using a fast compressor on top of it too, like LZ4.

**Comment by TimonPost** [comment]
I will do. I think I eventually do need my own serializer. The problem with game networking is that every byte is one too much. It should be as short as possible. With compression and delta encoding ontop of it. However, thanks for the suggestion, it is more clear now.

**Comment by Boscop** [comment]
Yes, I think it makes sense to also put effort into minimizing the json repr.
How about shortening the enum variants to one letter for serialization:
```rust
enum DiffCommandField {
    E, // Enter
    V, // Value
    R, // Remove
    A, // AddKey
    N, // EnterKey
    M, // RemoveKey
    X, // Exit
}

pub enum DiffPathElementValue<'a> {
    /// A struct field
    #[serde(borrow)]
    F(Cow<'a, str>), // Field
    I(u16),          // FieldIndex
    C(usize),        // CollectionIndex
    A,               // AddToCollection
}

**Comment by TimonPost** [comment]
Sounds like a good plan to me. We do have to check what potential future developments are. We should avoid changing those things too much since user might depend on it. This library is not used that heavily yet so now we are yet free to do certain renames.

**Comment by kabergstrom** [comment]
I think revisiting your goals may be a good idea here. If your goal is to minimize the size of your messages, the JSON format is not a good option - use a binary format instead. Binary encodings are pretty optimal for size right now with varint encodings (messagepack for example). I agree that the current encoding is not very readable and doesn't mesh well with text formats though, so I think a more fruitful goal is to improve the text encoding by utilizing hierarchical structures already present in these formats.

An enum variant entry in an array is represented in JSON as an object in an array: `{"VariantName":val},`. If you shorten the name to a single character, you will still be using about 6 characters, or 6 bytes, for each command.

The command stream encodes a hierarchical traversal. JSON is inherently a hierarchical format, so the following command stream:
`[Enter("field_of_greatness"), Value(5.0)]` can be transformed and represented in JSON with a map notation:
`{ "field_of_greatness": 5.0 }`
This will end up a lot more natural and readable. An example with deeper hierarchy:
`{ "big_struct":  { "field_a": 8, "field_b": "value" } }`

I would happily merge a PR that can produce that kind of structure for text formats using map serialization in serde.

**Comment by aclysma** [comment]
I agree with @kabergstrom. JSON is ultimately a human-readable representation. Making field names single-letter-length doesn't produce a byte-efficient encoding. But it does make what should be a human readable format much harder to read.

Further, this library is encoding the names of all the variables, which is not byte-efficient either. These could potentially be hashed, but again that's maybe not something we'd want to do in a format that's used for human-readable data. If someone HAS to use json and they don't care about readability, they can encode binary in json using base64.

For more flexibility it might be possible to add a trait which DiffContext implements. This would allow an end user to hook functions like `push_field`, `push_field_index`, `save_value`, etc.

I also agree being able to store this data in a more json-native way as @kabergstrom described would be a really nice improvement. This could potentially be added as an additional layer that produces and consumes the current output format. Or perhaps an implementation of that new trait could do it directly as it catches `push_field` etc.
