### ISSUE TITLE
Split up lib.rs

### ISSUE THREAD

**Issue by TimonPost** [amethyst/serde-diff#13]
I had an idea to split up `lib.rs`. For this I had the following structure in mind:

```
| src
| --- lib.rs
| --- difference.rs
| --- apply.rs
| --- implementation.rs
| --- counting-serialize.rs
```

The current `lib.rs` is quite big. It will be easier to read when dividing the code into multiple files.

What do you think? Would you bother if I create a PR for this?

**Comment by kabergstrom** [comment]
Sounds good to me! What did you want to put in lib.rs and implementation.rs?

**Comment by TimonPost** [comment]
lib.rs will contain the `SerializeDiff` trait and reexports to make no API changes. And in implementations.rs we will put all the type mappings and macro's.

**Comment by kabergstrom** [comment]
Sounds good to me!
