### ISSUE TITLE
Support derive for enums

### ISSUE THREAD

**Issue by kabergstrom** [amethyst/serde-diff#6]
Currently the derive proc macro does not support enums.

**Comment by Boscop** [comment]
For enum support, if the discriminant is different, should the whole rest of the enum be treated as different even if it's equal?
E.g.:
```rust
enum Foo {
	A(T),
	B(T),
	C(Bar),
}
```
If it changed from `A(T)` to `B(T)` but same instance of `T`, it makes sense to view only the discriminant as changed.
But then the diffing for enums would have to view enums as `(usize, <union of all variants' members>)` but then it can't diff that union in a type-safe way.. 

The easiest would be if we just treat the whole enum as different if the discriminant is different, forcing the user to change the enum to `enum Foo { AorB(AorB, T), C(Bar) } enum AorB { A, B }` if they want to optimize the above case..

Or is there a way to get this optimization by default, in a type-safe way?
