### ISSUE TITLE
When deriving `SerdeDiff`, allow specifying if the impl should make the type `opaque`

### ISSUE THREAD

**Issue by Boscop** [amethyst/serde-diff#9]
1. Currently, one has to write `simple_serde_diff!(Foo);` to make `Foo` opaque during diffing.
It would be nicer (regarding API-design) to be able to specify it when deriving `SerdeDiff` like:
```rust
#[derive(SerdeDiff)]
#[serde_diff(opaque)]
struct Foo { ... }
```

2. For making individual fields opaque (instead of their whole type in all occurrences), currently the syntax is `#[serde_diff(inline)]`, but `#[serde_diff(opaque)]` would be more intuitive/obvious for someone reading the code, and would be the same attribute as for a whole type (but on a field).

**Comment by kabergstrom** [comment]
I implemented this here: https://github.com/amethyst/serde-diff/commit/b18e10da34bd0c8892fc942fe1bfaf3b8bf3d865

Sorry forgot to mention it

**Comment by Boscop** [comment]
Ah, sorry :)

**Comment by Boscop** [comment]
@kabergstrom Btw, I think it would make sense to make it a compile warning (or even error) if `#[serde_diff(opaque)]` is specified on both the struct and a field (because it was probably a mistake to have it also on the field).
